DROP TABLE IF EXISTS student;
CREATE TABLE IF NOT EXISTS student
(
    ID          SERIAL NOT NULL,
    FIRST_NAME  VARCHAR(255),
    LAST_NAME   VARCHAR(255),
    MIDDLE_NAME VARCHAR(255),
    BIRTH_DATE  DATE,
    GROUP_NAME  VARCHAR(225),

    PRIMARY KEY (ID)
)